import { useEffect, useState } from "react";
import { Link } from "@tanstack/react-router";
import { ArrowUpRight, ChevronDown } from "lucide-react";
import { cn } from "@/lib/utils";
import { ScrollReveal } from "@/hooks/use-scroll-animation";
import { servicesData } from "@/data/services";
import { WebpImage } from "@/components/WebpImage";

/** Fallback source, the JPEG candidates the `<img>` picks from, the WebP
 *  candidates the `<source>` offers, and the intrinsic size of `src`. Kept as
 *  one object per rendered image so the ladders can never drift out of sync with
 *  each other — and because the source aspect is no longer uniform (see below),
 *  the intrinsic pair cannot be hoisted into shared constants any more. */
type ServiceImage = {
  src: string;
  srcSet: string;
  webpSrcSet: string;
  width: number;
  height: number;
};

/**
 * Candidates for the service-card preview.
 *
 * The desktop preview renders at ~664px CSS inside the 1200px container
 * (aspect-16/9, object-cover); mobile accordion images are full-width
 * (aspect-16/10, object-cover). So the ladder is:
 * - 480w  — mobile 1x–2x (a 390px phone paints a ~342px slot)
 * - 768w  — mobile 2x edge and desktop 1x (~664px)
 * - 1200w — 2x desktop (~1330px); the build-generated full-size `.webp` twin,
 *            which is the widest thing the 1200px source can honestly give
 *
 * `src` is the 768w JPEG rather than the 1200px original, so a browser that
 * skips the WebP `<source>` — or srcset entirely — still downloads ~50KB
 * instead of the 293-445KB PNG. The originals stay the variant *source* and are
 * never a rendered candidate.
 *
 * Every URL below is generated by the RESPONSIVE_VARIANTS records in
 * scripts/optimize-images.mjs. Never add a candidate here without the matching
 * record there, or the browser 404s — a `<source>` that resolves to nothing is
 * a broken image, not a fallback.
 */
const SVC_SIZES = "(max-width: 768px) 100vw, 664px";

/*
 * `width`/`height` are the intrinsic size of the 768w variant, emitted so the
 * browser reserves the box before the bytes land. Both slots crop with
 * object-cover inside a fixed-aspect container, so these only supply the aspect
 * hint — kept per image rather than hoisted because the hint has to stay honest
 * if a source is ever swapped. Three sources are 16:9 supplied artwork under
 * images/ (768x432); both brand-identity plates are 3:2 (768x512) and are
 * cropped by object-cover like the rest.
 *
 * Each slug maps to an ARRAY because a service can have more than one plate:
 * brand-identity ships two and they rotate inside the single preview card. One
 * entry means no carousel — ServiceMedia hides the dots and skips the timer
 * rather than special-casing the slug.
 *
 * Regenerate the -480/-768 variants from the source whenever a supplied image is
 * replaced or added — they are committed build output, and `vite dev` serves
 * them straight off disk rather than deriving them, so a swapped source
 * otherwise keeps rendering the old art. The RESPONSIVE_VARIANTS records in
 * scripts/optimize-images.mjs have to list the new file too, or the URLs below
 * 404 (a `<source>` that resolves to nothing is a broken image, not a fallback).
 */
const svcImages: Record<string, ServiceImage[]> = {
  "ui-ux-design": [
    {
      src: "/images/uiux-768.jpg",
      srcSet: "/images/uiux-480.jpg 480w, /images/uiux-768.jpg 768w",
      webpSrcSet: "/images/uiux-480.webp 480w, /images/uiux-768.webp 768w, /images/uiux.webp 1200w",
      width: 768,
      height: 432,
    },
  ],
  "website-development": [
    {
      src: "/images/website-development-768.jpg",
      srcSet: "/images/website-development-480.jpg 480w, /images/website-development-768.jpg 768w",
      webpSrcSet:
        "/images/website-development-480.webp 480w, /images/website-development-768.webp 768w, /images/website-development.webp 1200w",
      width: 768,
      height: 432,
    },
  ],
  "brand-identity": [
    {
      src: "/images/brand-identity-768.jpg",
      srcSet: "/images/brand-identity-480.jpg 480w, /images/brand-identity-768.jpg 768w",
      webpSrcSet:
        "/images/brand-identity-480.webp 480w, /images/brand-identity-768.webp 768w, /images/brand-identity.webp 1200w",
      width: 768,
      height: 512,
    },
    {
      src: "/images/brand-identity-2-768.jpg",
      srcSet: "/images/brand-identity-2-480.jpg 480w, /images/brand-identity-2-768.jpg 768w",
      webpSrcSet:
        "/images/brand-identity-2-480.webp 480w, /images/brand-identity-2-768.webp 768w, /images/brand-identity-2.webp 1200w",
      width: 768,
      height: 512,
    },
  ],
  // Source is `marketing-creative.jpeg` (singular) while the slug is
  // `marketing-creatives` — the variant names follow the FILE, so keep the
  // ladder on `marketing-creative-*`.
  "marketing-creatives": [
    {
      src: "/images/marketing-creative-768.jpg",
      srcSet: "/images/marketing-creative-480.jpg 480w, /images/marketing-creative-768.jpg 768w",
      webpSrcSet:
        "/images/marketing-creative-480.webp 480w, /images/marketing-creative-768.webp 768w, /images/marketing-creative.webp 1200w",
      width: 768,
      height: 432,
    },
  ],
};

interface WhatWeDoItem {
  index: string;
  slug: string;
  title: string;
  description: string;
  images: ServiceImage[];
}

const services: WhatWeDoItem[] = servicesData
  .map((s, i) => ({
    index: String(i + 1).padStart(2, "0"),
    slug: s.slug,
    title: s.shortTitle,
    description: s.tagline,
    images: svcImages[s.slug],
  }))
  // `images.length` rather than `images`: a slug with an empty array would
  // otherwise pass and render a preview with nothing in it.
  .filter((s): s is WhatWeDoItem => Boolean(s.images?.length));

const DEFAULT_SERVICE: WhatWeDoItem = {
  index: "01",
  slug: "ui-ux-design",
  title: "UI/UX Design",
  description:
    "We design intuitive, user-friendly websites and apps that people enjoy using and come back to.",
  images: svcImages["ui-ux-design"] as ServiceImage[],
};

function AccentBar({ active }: { active: boolean }) {
  return (
    <span
      aria-hidden="true"
      className={cn(
        "absolute left-0 top-1/2 h-9 w-1 -translate-y-1/2 rounded-full bg-primary transition-all duration-300 ease-out",
        active
          ? "scale-y-100 opacity-100"
          : "scale-y-50 opacity-0 group-hover:scale-y-100 group-hover:opacity-40",
      )}
    />
  );
}

/** How long each plate of a multi-image service stays up. */
const ROTATE_MS = 5200;

function usePrefersReducedMotion() {
  const [reduced, setReduced] = useState(false);

  useEffect(() => {
    const mq = window.matchMedia("(prefers-reduced-motion: reduce)");
    const update = () => setReduced(mq.matches);
    update();
    mq.addEventListener("change", update);
    return () => mq.removeEventListener("change", update);
  }, []);

  return reduced;
}

/**
 * Which plate of the active service is showing, advancing on a timer.
 *
 * `running` is the caller's "this preview is actually on screen" signal — the
 * desktop panel passes true only for the selected service, and the mobile panel
 * passes whether its accordion row is open — which keeps a closed or off-screen
 * preview from spending a timer that swaps images nobody sees.
 *
 * Switching services resets the position by remounting instead of by an effect:
 * the desktop caller keys `ServiceMedia` on the slug, so React gives the new
 * service a fresh state rather than a cascading render to correct the old one.
 *
 * A `count` of 1 is not a special case in the caller: no timer is installed and
 * no dots render, so a single-plate service behaves exactly as it did before.
 */
function usePlateIndex(count: number, running: boolean) {
  const [index, setIndex] = useState(0);
  const reduced = usePrefersReducedMotion();

  useEffect(() => {
    if (count < 2 || !running || reduced) return;
    const id = window.setInterval(() => setIndex((i) => (i + 1) % count), ROTATE_MS);
    return () => window.clearInterval(id);
  }, [count, running, reduced]);

  // The modulo keeps the index in range for the render that happens before a
  // `count` change (a dot click racing a service switch) has settled.
  return [count > 0 ? index % count : 0, setIndex] as const;
}

/**
 * Dots for a multi-plate preview, drawn over the frame's bottom-right corner so
 * both slots can drop them in without the caller's layout having to reserve
 * space for them. The translucent pill is what makes them legible over
 * arbitrary artwork; a bare dot has no guaranteed contrast.
 */
function PlateDots({
  count,
  index,
  onSelect,
  title,
}: {
  count: number;
  index: number;
  onSelect: (i: number) => void;
  title: string;
}) {
  if (count < 2) return null;

  return (
    <div
      role="group"
      aria-label={`${title} images`}
      className="absolute right-3 bottom-3 flex items-center gap-1.5 rounded-full bg-background/70 px-2.5 py-2 backdrop-blur-sm"
    >
      {Array.from({ length: count }, (_, i) => (
        <button
          key={i}
          type="button"
          onClick={() => onSelect(i)}
          aria-label={`Show image ${i + 1} of ${count}`}
          aria-current={i === index}
          className={cn(
            "h-1.5 cursor-pointer rounded-full transition-all duration-300 ease-out",
            i === index
              ? "w-5 bg-primary"
              : "w-1.5 bg-muted-foreground/50 hover:bg-muted-foreground",
          )}
        />
      ))}
    </div>
  );
}

/**
 * The service preview: a fixed-aspect frame holding every plate of the active
 * service, crossfaded, plus the dots that drive it. Shared by the desktop panel
 * and the mobile accordion so both rotate identically — the only difference is
 * the aspect class the caller passes in.
 */
function ServiceMedia({
  item,
  running,
  frameClassName,
  overlayClassName,
  sizes,
}: {
  item: WhatWeDoItem;
  running: boolean;
  frameClassName: string;
  /** Optional hairline drawn over the frame; the desktop card has one, the
   *  mobile panel's frame is already inset in a bordered card and does not. */
  overlayClassName?: string;
  sizes: string;
}) {
  // Pointer devices get a pause on hover: the desktop list swaps the selected
  // service on mouseenter, so without this the plate would advance out from
  // under a visitor who is reading it.
  const [hovered, setHovered] = useState(false);
  const [index, setIndex] = usePlateIndex(item.images.length, running && !hovered);

  return (
    <div
      className={cn("relative overflow-hidden", frameClassName)}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
    >
      {item.images.map((img, i) => (
        <div
          key={img.src}
          aria-hidden={i !== index}
          className={cn(
            "absolute inset-0 transition-opacity duration-300 ease-out",
            i === index ? "opacity-100" : "opacity-0",
          )}
        >
          <WebpImage
            src={img.src}
            srcSet={img.srcSet}
            webpSrcSet={img.webpSrcSet}
            sizes={sizes}
            width={img.width}
            height={img.height}
            // Only the visible plate is named; the others are decorative
            // duplicates of the same service, so announcing all of them would
            // read the service name once per plate.
            alt={i === index ? item.title : ""}
            loading="lazy"
            decoding="async"
            className="h-full w-full object-cover"
          />
        </div>
      ))}
      {overlayClassName ? (
        <div className={cn("pointer-events-none absolute inset-0", overlayClassName)} />
      ) : null}
      <PlateDots count={item.images.length} index={index} onSelect={setIndex} title={item.title} />
    </div>
  );
}

function DesktopAccordion({ active, onSelect }: { active: number; onSelect: (i: number) => void }) {
  return (
    <div className="flex flex-col pt-28">
      {services.map((s, i) => {
        const isActive = i === active;
        const isLast = i === services.length - 1;
        return (
          // The heading carries the service name for assistive tech and the
          // document outline; the button stays inside it, which is the standard
          // accordion pattern. `tracking-[-0.04em]` re-states the body tracking
          // the button used to inherit directly, because styles.css applies a
          // tighter -0.025em to every h1-h6 and would otherwise loosen the
          // index and title spans.
          <h3 key={s.slug} className="tracking-[-0.04em]">
            <button
              type="button"
              onMouseEnter={() => onSelect(i)}
              onClick={() => onSelect(i)}
              aria-pressed={isActive}
              className={cn(
                "group relative flex w-full cursor-pointer items-center gap-5 py-7 pr-2 text-left transition-all duration-300 ease-out",
                // `last:border-b-0` cannot live on the button any more: it is the
                // heading's only child, so `:last-child` would strip every row's
                // divider. Resolved from the index instead.
                isLast ? "border-b-0" : "border-b",
                isActive ? "border-primary/30 lg:pl-5" : "border-border lg:pl-0 lg:hover:pl-3",
              )}
            >
              <AccentBar active={isActive} />
              <span
                aria-hidden="true"
                className={cn(
                  "type-label shrink-0 transition-colors duration-300 ease-out",
                  isActive
                    ? "font-extrabold text-primary"
                    : "text-muted-foreground group-hover:text-primary",
                )}
              >
                {s.index}
              </span>
              <span
                className={cn(
                  "flex-1 font-display text-xl transition-colors duration-300 ease-out md:text-2xl",
                  isActive
                    ? "font-extrabold text-foreground"
                    : "font-semibold text-muted-foreground/70 group-hover:text-foreground",
                )}
              >
                {s.title}
              </span>
              <ArrowUpRight
                aria-hidden="true"
                className={cn(
                  "size-5 shrink-0 transition-all duration-300 ease-out",
                  isActive
                    ? "-translate-y-0 translate-x-0 text-primary opacity-100"
                    : "-translate-y-1 translate-x-1 text-muted-foreground/50 opacity-0 group-hover:text-primary group-hover:opacity-100",
                )}
              />
            </button>
          </h3>
        );
      })}
    </div>
  );
}

function MobileAccordion({
  active,
  onSelect,
}: {
  active: number | null;
  onSelect: (i: number | null) => void;
}) {
  return (
    <div className="space-y-4">
      {services.map((s, i) => {
        const isOpen = i === active;
        return (
          <div
            key={s.slug}
            className={cn(
              "overflow-hidden rounded-2xl border bg-card transition-colors duration-300 ease-out",
              isOpen ? "border-primary/50" : "border-border",
            )}
          >
            {/* Same accordion pattern as the desktop list: heading outside,
                button inside. `tracking-[-0.04em]` for the reason given there —
                the title span's own `tracking-tight` already pins the visible
                text, this keeps the index label matching. */}
            <h3 className="tracking-[-0.04em]">
              <button
                type="button"
                onClick={() => onSelect(isOpen ? null : i)}
                aria-expanded={isOpen}
                aria-controls={`service-panel-${s.slug}`}
                className="flex w-full cursor-pointer items-center gap-4 p-6 text-left"
              >
                <span
                  className={cn(
                    "type-label shrink-0 transition-colors duration-300 ease-out",
                    isOpen ? "font-extrabold text-primary" : "text-muted-foreground",
                  )}
                >
                  {s.index}
                </span>
                <span
                  className={cn(
                    "flex-1 font-display text-lg font-bold tracking-tight transition-colors duration-300 ease-out",
                    isOpen ? "text-foreground" : "text-foreground/70",
                  )}
                >
                  {s.title}
                </span>
                <ChevronDown
                  aria-hidden="true"
                  className={cn(
                    "size-5 shrink-0 transition-transform duration-300 ease-out",
                    isOpen ? "rotate-180 text-primary" : "text-muted-foreground",
                  )}
                />
              </button>
            </h3>

            <div
              id={`service-panel-${s.slug}`}
              className={cn(
                "grid transition-[grid-template-rows,opacity] duration-300 ease-out",
                isOpen ? "grid-rows-[1fr] opacity-100" : "grid-rows-[0fr] opacity-0",
              )}
            >
              <div className="overflow-hidden">
                <div className="px-6 pb-6">
                  <ServiceMedia
                    item={s}
                    running={isOpen}
                    frameClassName="relative aspect-[16/10] overflow-hidden rounded-xl"
                    sizes={SVC_SIZES}
                  />
                  <p className="mt-4 text-base leading-relaxed text-muted-foreground">
                    {s.description}
                  </p>
                  <Link
                    to="/services/$slug"
                    params={{ slug: s.slug }}
                    className="group mt-4 inline-flex items-center gap-2 text-sm font-bold text-primary transition-colors duration-200 ease-out hover:text-primary-hover"
                  >
                    Explore {s.title}
                    <ArrowUpRight className="size-4 transition-transform duration-250 ease-out group-hover:translate-x-0.5 group-hover:-translate-y-0.5" />
                  </Link>
                </div>
              </div>
            </div>
          </div>
        );
      })}
    </div>
  );
}

export function WhatWeDo() {
  const [active, setActive] = useState<number | null>(0);
  const item = services[active ?? 0] ?? DEFAULT_SERVICE;

  return (
    <section
      id="services"
      className="mx-auto w-full max-w-[1200px] scroll-mt-24 px-6 pt-20 pb-20 lg:pt-24 lg:pb-24"
    >
      <ScrollReveal>
        <p className="eyebrow">What we do</p>
        <h2 className="mt-5 font-display text-4xl font-extrabold tracking-tight sm:text-5xl">
          Services that drive brands forward
        </h2>
      </ScrollReveal>

      <div className="mt-14 hidden grid-cols-1 items-start gap-12 lg:grid lg:grid-cols-5 lg:gap-16">
        <ScrollReveal direction="left" className="lg:col-span-2">
          <DesktopAccordion active={active ?? 0} onSelect={setActive} />
        </ScrollReveal>
        <ScrollReveal direction="right" className="lg:col-span-3">
          <div className="overflow-hidden rounded-3xl border border-border bg-card shadow-card">
            <ServiceMedia
              // Keyed on the slug so selecting a different service remounts the
              // preview on that service's first plate. Without it the plate
              // index would carry over — landing on the brand-identity service
              // would open mid-rotation, or out of range entirely for the
              // single-plate services.
              key={item.slug}
              item={item}
              running
              frameClassName="aspect-[16/9]"
              overlayClassName="rounded-3xl ring-1 ring-inset ring-black/10"
              sizes={SVC_SIZES}
            />

            <div className="p-5 md:p-6">
              <div key={item.index} className="sk-fade-up">
                <div className="flex items-center gap-3">
                  <span className="type-label font-extrabold text-primary">{item.index}</span>
                  <span className="h-px flex-1 bg-border" />
                  <span className="type-caption text-muted-foreground">Our services</span>
                </div>
                {/* Was an <h3>, which made the active service's name a second
                heading for the same text. The name is already the heading in
                the list that drives this panel, so this repeats the styling
                without repeating the semantics. */}
                <p className="mt-2.5 font-display text-xl font-extrabold tracking-tight">
                  {item.title}
                </p>
                <p className="mt-2 max-w-sm text-sm leading-relaxed text-muted-foreground">
                  {item.description}
                </p>
              </div>

              <Link
                to="/services/$slug"
                params={{ slug: item.slug }}
                className="group mt-4 inline-flex items-center gap-2 text-sm font-bold text-primary transition-colors duration-200 ease-out hover:text-primary-hover"
              >
                Explore {item.title}
                <ArrowUpRight className="size-4 transition-transform duration-250 ease-out group-hover:translate-x-0.5 group-hover:-translate-y-0.5" />
              </Link>
            </div>
          </div>
        </ScrollReveal>
      </div>

      <div className="mt-10 lg:hidden">
        <MobileAccordion active={active} onSelect={setActive} />
      </div>
    </section>
  );
}
