/**
 * Ambient declarations for the virtual modules served by plugins in
 * vite.config.ts. Kept in one file so the config stays the single place that
 * decides what those modules contain.
 */

/**
 * Ordered hero mockup plates from `public/carousel/`, as served URLs.
 *
 * Generated by the `skedio:carousel-manifest` plugin from the files matching
 * `m<n>.<png|jpe?g|webp|avif>` in that folder, sorted by `n`. Empty when the
 * folder is absent or holds no plates.
 */
declare module "virtual:carousel-manifest" {
  const plates: string[];
  export default plates;
}
